weak tud_descriptor_string_cb and adjuest epin and epout
adafruit/Adafruit_TinyUSB_ArduinoCore pull request #12
Opened 2020-08-19 03:42 UTC by Pillar1989

2020-08-21 03:55 UTC, hathach requested changes
weak callback declared is not needed, and I don't see why we need to change the order of EPs

2020-08-21 03:55 UTC, hathach commented on Adafruit_USBD_Device.cpp
> +TU_ATTR_WEAK uint16_t const* tud_descriptor_string_cb(uint8_t index, uint16_t langid);
not needed since it is implemented already.

2020-08-21 03:55 UTC, hathach commented on tinyusb/src/device/usbd.h
> +  7, TUSB_DESC_ENDPOINT, _epin, TUSB_XFER_INTERRUPT, U16_TO_U8S_LE(_epsize), _ep_interval,\
why would you want to change the order ?

2020-08-21 03:55 UTC, hathach commented on Adafruit_USBD_CDC.h
> +        void setBaud(uint32_t baud) {  _baud_rate = baud; }
These aren't Arduino std AP, it got ignored anyway. I don't see why we would need it

2020-08-27 00:21 UTC, Pillar1989 commented
Sorry to bother you, but I'll do it myself.

2020-08-27 00:21 UTC, closed without merging